name: Deploy ASP.NET Core

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: webappAbschluss
  AZURE_WEBAPP_PATH: '.'
  DOTNET_VERSION: '7.0.105'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Dotnet build + publish
        run: |
          dotnet build --configuration Release
          dotnet publish -c Release -o '${{ env.AZURE_WEBAPP_PATH }}/myapp'

      #- name: Deploy to App Service
      #  uses: azure/webapps-deploy@v2
      #  with:
      #    app-name: ${{ env.AZURE_WEBAPP_NAME }}
      #    publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
      #    package: '${{ env.AZURE_WEBAPP_PATH }}/myapp'
